### ISSUE TITLE
Ubuntu 14.04 webhook init fails

### ISSUE THREAD

**Issue by te206676** [acidprime/r10k#105]
When running the PE master and r10k on Ubuntu 14.04 the webhook init script will fail.

Line's 17/18 of the erb template include
# Source function library.
. /etc/rc.d/init.d/functions

Is it sufficient to ln -s /lib/lsb/functions to /etc/rc.d/init.d/functions? This appears to allow the code to execute, but I'm not sure it is functionally equivalent.

It might be worth stating that the daemon package has to be installed through apt-get in order to run this code without error as well.

**Comment by acidprime** [comment]
https://github.com/acidprime/r10k/pull/118
