### ISSUE TITLE
Dependency disappeared from forge.

### ISSUE THREAD

**Issue by AlexRRR** [acidprime/r10k#116]
Hello! Thanks for your module I've been using it for a while now. Just a heads up for everyone... it seems that the dependency on *"mhuffnagle/make"* has disappeared from puppetforge 

https://forge.puppetlabs.com/mhuffnagle/make returns 404

I know they have been fiddling with adding ratings to the modules and what not, but r10k complains loudly now about this not working.

Cheers,

**Comment by AlexRRR** [comment]
Oh.. it is also gone from github.

**Comment by ghoneycutt** [comment]
https://github.com/ghoneycutt/puppet-modules/blob/master/Puppetfile#L59-63

I'm using Element84/puppet-make with a specific commit hash in my Puppetfile to resolve this dependency. @AlexRRR this could be a short term fix for you.

@acidprime was going to suggest using that one in your Modulefile, but it appears to be abandoned, only supports EL and Ubuntu, and the tests don't actually test the functionality.

I could put together a module for it, though first do you know of any that already exist? Could not find anything on the forge.

**Comment by acidprime** [comment]
This has been resolved in https://github.com/acidprime/r10k/releases/tag/v2.5.2 and https://forge.puppetlabs.com/zack/r10k/2.5.2/readme

**Comment by acidprime** [comment]
I will likely remove this as a dep in 3.x series of the module as make is not required in v1 of r10k any more and its probably been long enough now

**Comment by ghoneycutt** [comment]
Awesome! I can remove a few dependencies in my Puppetfile that are just for r10k :)
