### ISSUE TITLE
Module upgrade does not upgrade r10k gem

### ISSUE THREAD

**Issue by ghoneycutt** [acidprime/r10k#126]
Upgraded module to 2.6.1 and it did not update the r10k gem from 1.4.0 to 1.4.1 as expected

**Comment by acidprime** [comment]
Can you give me an example of your class declaration so I can reproduce, most of the install methods are a package resource based so I would curios what it did not upgrade it

**Comment by acidprime** [comment]
closing , feel free to reopen if you anyone has steps to reproduce.
