### ISSUE TITLE
pre_commit ruby script fails puppet-lint if you are in the wrong working directory

### ISSUE THREAD

**Issue by oznah** [acidprime/r10k#130]
puppet-lint test fails with "foo::bar not in autoload module layout" error.

**Comment by oznah** [comment]
Adding absolute path to puppet_lint function fixed for me.

```
def puppet_lint(file)
       # system('puppet-lint ' + file)
       system('puppet-lint ' + File.absolute_path(file))
```

**Comment by ghoneycutt** [comment]
submitted PR #131 for this

**Comment by acidprime** [comment]
Re-opening this as that PR was for the Rakefile, but the issue referenced is for the pre-commit script in the files directory of the module.
