### ISSUE TITLE
include r10k::mcollective fails with error on debian with puppet FOSS

### ISSUE THREAD

**Issue by hasc** [acidprime/r10k#136]
Hi,

thanks for sharing this module. When I add include r10k::mcollective to one of my profiles I am getting the following error:

Error: Could not set 'file' on ensure: No such file or directory - /usr/share/mcollective/plugins/mcollective/agent/r10k.ddl20150223-2961-1cq6xnp.lock at 23:/etc/puppet/modules/r10k/manifests/mcollective.pp
Error: Could not set 'file' on ensure: No such file or directory - /usr/share/mcollective/plugins/mcollective/agent/r10k.ddl20150223-2961-1cq6xnp.lock at 23:/etc/puppet/modules/r10k/manifests/mcollective.pp
Wrapped exception:
No such file or directory - /usr/share/mcollective/plugins/mcollective/agent/r10k.ddl20150223-2961-1cq6xnp.lock
Error: /Stage[main]/R10k::Mcollective/File[/usr/share/mcollective/plugins/mcollective/agent/r10k.ddl]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /usr/share/mcollective/plugins/mcollective/agent/r10k.ddl20150223-2961-1cq6xnp.lock at 23:/etc/puppet/modules/r10k/manifests/mcollective.pp
Notice: /Stage[main]/R10k::Mcollective/File[/usr/share/mcollective/plugins/mcollective/agent/r10k.rb]: Dependency File[/usr/share/mcollective/plugins/mcollective/agent/r10k.ddl] has failures: true
Warning: /Stage[main]/R10k::Mcollective/File[/usr/share/mcollective/plugins/mcollective/agent/r10k.rb]: Skipping because of failed dependencies

The node is based on the latest version of debian wheezy. Also I am NOT using puppet enterprise but just puppet. I did not get from the documentation whether the mcollective approach in general only works for puppet enterprise or whether it is just the Webhook Support which is somehow limited to puppet enterprise.

Having that said, I am not sure what the problem is. Did I miss any pre-requirements regarding setup of mcollective or is this indeed an issue? 

Thanks in advance!

Best
hasc

**Comment by acidprime** [comment]
This is the code in question

https://github.com/acidprime/r10k/blob/master/manifests/params.pp#L80-L83


We don't manage the parent directory and so it looks as though that directory does not exist on your system.

**Comment by hasc** [comment]
Thanks for the quick response. Right, the directory does not exist. From the documentation I was not aware that I need to setup mcollective separately. Sorry to bother you with this, but does the mcollective hook only work with the enterprise edition? This is what I still do not understand. Thanks in advance. hasc

**Comment by acidprime** [comment]
@hasc yeah this module does not setup mcollective for you, the agent I believe should work in FOSS but the webhook is currently hardcoded to only work in PE. You might check out https://forge.puppetlabs.com/wdijkerman/webhook

**Comment by hasc** [comment]
Thanks for clarification!
