### ISSUE TITLE
web hook does not work for non-mco install

### ISSUE THREAD

**Issue by logicminds** [acidprime/r10k#139]
I get the following errors when I apply this to my pe master system.

```puppet
# Instead of running via mco, run r10k directly
class {'r10k::webhook::config':
  use_mcollective => false,
}

# The hook needs to run as root when not running using mcollective
# It will issue r10k deploy environment <branch_from_gitlab_payload> -p
# When git pushes happen.
class {'r10k::webhook':
  user    => 'root',
  group   => '0',
  require => Class['r10k::webhook::config'],
}

```

```shell
Error: Could not start Service[webhook]: Execution of '/sbin/service webhook start' returned 1: Starting webhook: /usr/local/bin/webhook:50:in `initialize': No such file or directory - /var/lib/peadmin/.mcollective.d/peadmin-cert.pem (Errno::ENOENT)
	from /usr/local/bin/webhook:50:in `open'
	from /usr/local/bin/webhook:50:in `<main>'
[FAILED]
Wrapped exception:



Execution of '/sbin/service webhook start' returned 1: Starting webhook: /usr/local/bin/webhook:50:in `initialize': No such file or directory - /var/lib/peadmin/.mcollective.d/peadmin-cert.pem (Errno::ENOENT)
	from /usr/local/bin/webhook:50:in `open'
	from /usr/local/bin/webhook:50:in `<main>'
[FAILED]
Error: /Stage[main]/R10k::Webhook/Service[webhook]/ensure: change from stopped to running failed: Could not start Service[webhook]: Execution of '/sbin/service webhook start' returned 1: Starting webhook: /usr/local/bin/webhook:50:in `initialize': No such file or directory - /var/lib/peadmin/.mcollective.d/peadmin-cert.pem (Errno::ENOENT)
	from /usr/local/bin/webhook:50:in `open'
	from /usr/local/bin/webhook:50:in `<main>'
[FAILED]

```

**Comment by logicminds** [comment]
Not sure why it even needs mcollective if   use_mcollective => false,

**Comment by elyscape** [comment]
Yeah, this is a result of the webhook script always loading the PEM files even if they aren't needed.  I'll be doing a pretty big reworking of it soonish that'll fix this issue, among others.

**Comment by elyscape** [comment]
Oh, right.  It's loading the PEM files for SSL.

@logicminds, are you trying to use this with Puppet Open Source or do you have a Puppet Enterprise deployment that doesn't use MCollective for some reason?

**Comment by logicminds** [comment]
This is pe in a split install.  Pe admin is available and mco works just fine.

**Comment by elyscape** [comment]
What version of the module are you using?  Versions before 2.6.0 could fail to create the necessary certificate file before starting the service, and version 2.6.3 improved the ordering further.

**Comment by logicminds** [comment]
I am using version 2.6.3 of the r10k puppet module

**Comment by elyscape** [comment]
I think I have a fix.  Can you try editing manifests/webhook.pp and replacing this line towards the bottom:
```puppet
content => file('/etc/puppetlabs/puppet/ssl/certs/pe-internal-peadmin-mcollective-client.pem'),
```
with this?
```puppet
source => '/etc/puppetlabs/puppet/ssl/certs/pe-internal-peadmin-mcollective-client.pem',
```
Let me know if that works and, if it does, I'll make a PR to have it pushed into the module proper.

**Comment by logicminds** [comment]
```

Error: Could not start Service[webhook]: Execution of '/sbin/service webhook start' returned 1: Starting webhook: /usr/local/bin/webhook:50:in `initialize': Permission denied - /var/lib/peadmin/.mcollective.d/peadmin-cert.pem (Errno::EACCES)
	from /usr/local/bin/webhook:50:in `open'
	from /usr/local/bin/webhook:50:in `<main>'
[FAILED]
Wrapped exception:
Execution of '/sbin/service webhook start' returned 1: Starting webhook: /usr/local/bin/webhook:50:in `initialize': Permission denied - /var/lib/peadmin/.mcollective.d/peadmin-cert.pem (Errno::EACCES)
	from /usr/local/bin/webhook:50:in `open'
	from /usr/local/bin/webhook:50:in `<main>'
[FAILED]
Error: /Stage[main]/R10k::Webhook/Service[webhook]/ensure: change from stopped to running failed: Could not start Service[webhook]: Execution of '/sbin/service webhook start' returned 1: Starting webhook: /usr/local/bin/webhook:50:in `initialize': Permission denied - /var/lib/peadmin/.mcollective.d/peadmin-cert.pem (Errno::EACCES)
	from /usr/local/bin/webhook:50:in `open'
	from /usr/local/bin/webhook:50:in `<main>'
[FAILED]
```

Same error,  but it looks like the init script is looking for /var/lib/peadmin/.mcollective.d/peadmin-cert.pem  when it should be /var/lib/peadmin/.mcollective.d/peadmin-public.pem

**Comment by logicminds** [comment]
This is the web hook config file

```yaml
---
  user: puppet
  pass: puppet
  bind_address: "0.0.0.0"
  port: "8088"
  certname: peadmin
  client_timeout: "120"
  discovery_timeout: "10"
  certpath: /var/lib/peadmin/.mcollective.d
  client_cfg: /var/lib/peadmin/.mcollective
  use_mco_ruby: false
  access_logfile: /var/log/webhook/access.log
  mco_logfile: /var/log/webhook/mco_output.log
  protected: true
  prefix: false
  prefix_command: "/bin/echo example"
  enable_ssl: true
  use_mcollective: false
  r10k_deploy_arguments: "-pv"

```

**Comment by elyscape** [comment]
No, peadmin-cert.pem is correct.  peadmin-public.pem is just the public key, but peadmin-cert.pem is an actual X509 certificate.  The webhook uses them for its SSL setup.  It would, however, be better to generate a new key pair for the webhook to use.  I'll look into making that happen.

In the meantime, please run `stat /var/lib/peadmin/.mcollective.d/peadmin-cert.pem` and paste the results here.

**Comment by logicminds** [comment]
stat: cannot stat `/var/lib/peadmin/.mcollective.d/peadmin-cert.pem': No such file or directory

It does not exist.  Is this something I can control via the web hook config file?

**Comment by acidprime** [comment]
@logicminds yeah this only works on a split install if you install in on the master, which host did you try to install it on?

**Comment by logicminds** [comment]
This is the master.  Only puppetdb and the console are on other hosts.  Besides doesn't make sense to install on a non master system.

**Comment by acidprime** [comment]
@logicminds what version of PE are you using?

**Comment by logicminds** [comment]
3.7.2 (Puppet Enterprise 3.7.0)

**Comment by acidprime** [comment]
@logicminds is this a compile master or the CA?

**Comment by logicminds** [comment]
CA and compile master are on this system.

**Comment by acidprime** [comment]
My guess is this is the offending line
https://github.com/acidprime/r10k/blob/master/manifests/webhook.pp#L57
I can push a patch to make that 1 as I think its failing because it was only equally checking 3.7.0 
https://docs.puppetlabs.com/references/latest/function.html#versioncmp

**Comment by logicminds** [comment]
```puppet
if versioncmp($::pe_version, '3.7.0') > 0 {
  notice('versioncompare: > 0')
}else {
  notice('versioncompare: < 0')

}

Notice: Scope(Class[main]): versioncompare: < 0
Notice: Compiled catalog for hostname.hidden.com in environment production in 0.05 seconds
Info: Applying configuration version '1424907669'
Notice: Finished catalog run in 0.17 seconds
```

**Comment by elyscape** [comment]
@acidprime Good catch.  Yeah, that should definitely be `>=` instead of `>`.

**Comment by logicminds** [comment]
is this fix still needed?

source => '/etc/puppetlabs/puppet/ssl/certs/pe-internal-peadmin-mcollective-client.pem',

**Comment by elyscape** [comment]
Probably not.

**Comment by acidprime** [comment]
@logicminds @elyscape as I recall I did not use source as the pe-puppet ownership trick only works when you run it with the file function for those certificates vs source copy which errors out. So no not needed and I don't think it would work anyway. @logicminds https://github.com/acidprime/r10k/releases/tag/v2.6.4 or the latest on the forge now should fix this

**Comment by acidprime** [comment]
Quick note for myself is this was a regression spawned by 2.6.0 commit ab4c58a8b4f807eb2199c631e6e683f21be6c285 and was not caught by spec as the tests were both missing and typo'ed.

**Comment by acidprime** [comment]
@logicminds thanks for reporting.
