### ISSUE TITLE
/var/log/webhook permissions not managed properly

### ISSUE THREAD

**Issue by ITBlogger** [acidprime/r10k#144]
Currently, module only manages permissions of the top folder, but not contents.

Please add recursive attribute to /var/log/webhook file resource or manually manage permissions for both of the log files.

**Comment by acidprime** [comment]
@ITBlogger thanks for the bug report, decided to sneak this in after some thought , please update the ticket if this resolves the issue for you. out of curitsoity how did you un into this as a problem as it would have been correct out of the box, do you have a script that `chown`s that var/log?

**Comment by elyscape** [comment]
A potential alternative option would be to set the sticky bit on the folder's permissions. Then recursive file management wouldn't be necessary.
