### ISSUE TITLE
Can we use this module with svn?

### ISSUE THREAD

**Issue by supriyawishesu** [acidprime/r10k#146]
Hi ,

we are using svn repository in our company. Can we use svn instead of git using your module? 

Please help me

**Comment by elyscape** [comment]
The value you give to `remote` is passed unmodified to `remote` in `r10k.yaml`, so you can use any URI type that is supported by r10k's configuration file.

**Comment by elyscape** [comment]
Some more info: r10k supports SVN repositories in the configuration file so long as you specify that they're SVN in your `sources` hash with `type => 'svn'`.
