### ISSUE TITLE
Sinatra gem required for PE webhook?

### ISSUE THREAD

**Issue by esalberg** [acidprime/r10k#154]
Is there a reason that the gem install for sinatra is only in the non-PE section of webhook.pp?  I can put in a pull request to add it (we don't have sinatra defined already, so it errors out with a dependency check), but I wanted to make sure that sinatra was still supposed to be a dependency for the PE webhook first.

**Comment by acidprime** [comment]
@esalberg good catch , please update the ticket if you still have any issues.

**Comment by esalberg** [comment]
I think the package needs to use the pe_gem provider instead of the gem provider (for Puppet Enterprise)?

My master is erroring with:
2015-04-22 13:53:31 -0400 /Package[sinatra] (err): Provider gem is not functional on this host

**Comment by acidprime** [comment]
@esalberg released a fix in 2.7.3

**Comment by esalberg** [comment]
Looks good!  Thank you.
