### ISSUE TITLE
Webhook does not install properly in PE 3.7

### ISSUE THREAD

**Issue by trevor-vaughan** [acidprime/r10k#164]
The webhook will not properly install in PE 3.7 due to the 'sinatra' gem not using the pe_gem provider.

https://github.com/acidprime/r10k/blob/master/manifests/webhook.pp#L52

If that is moved into the two blocks as appropriate, everything appears to work swimmingly.

**Comment by acidprime** [comment]
@trevor-vaughan can you verify what version of the module you are using?

**Comment by trevor-vaughan** [comment]
Hi Zack,

I'm using commit dceacf19f2d3bc1665efe0186a600012eb2b71b9.

Thanks,

Trevor

On Fri, May 8, 2015 at 3:48 PM, Zack Smith <notifications@github.com> wrote:

> @trevor-vaughan <https://github.com/trevor-vaughan> can you verify what
> version of the module you are using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acidprime/r10k/issues/164#issuecomment-100338693>.
>



-- 
Trevor Vaughan
Vice President, Onyx Point, Inc
(410) 541-6699
tvaughan@onyxpoint.com

-- This account not approved for unencrypted proprietary information --

**Comment by acidprime** [comment]
Yeah I believe I solved this a version or two ago, can you update, closing , please repo if you you have issues with https://github.com/acidprime/r10k/blob/1fa55680d63df718ad0fb81ca1ef1c9270a3146f/manifests/webhook.pp
