### ISSUE TITLE
Change git_ssl_verify parameter name

### ISSUE THREAD

**Issue by petems** [acidprime/r10k#165]
The parameter is `git_ssl_verify` but the value it's setting is `GIT_SSL_NO_VERIFY `

So git_ssl_verify => 'true' is actually saying "Make sure SSL is not verified"

Probably better to rename it to `git_no_ssl_verify` and add a deprecation to the old parameter, followed by removal in a major bump?

**Comment by acidprime** [comment]
makes sense to me
