### ISSUE TITLE
puppetconf_path is incorrect for puppet4

### ISSUE THREAD

**Issue by tykeal** [acidprime/r10k#187]
The AIO install for Puppet 4 does not use /etc/puppet for configs. Instead it's /etc/puppetlabs/puppet, since this is set incorrectly postrun_command and prerun_command do not work correctly unless a symlink link of /etc/puppet -> puppetlabs/puppet exists on the system.

**Comment by TheMeier** [comment]
From the 2.0 changelog
R10k 1.5.0 added '/etc/puppetlabs/r10k/r10k.yaml' to the paths checked while looking for a config file, in order to keep in convention with the rest of the Puppet Labs config files. In 2.0.0 the old location, '/etc/r10k.yaml', has been removed.

**Comment by TheMeier** [comment]
Actually /etc/r10k.yaml was re-added in 2.0.1
https://tickets.puppetlabs.com/browse/RK-118
anyway it will certainly wil be remoevd again in the future

**Comment by tykeal** [comment]
Hmm... maybe I wasn't particularly clear about the issue.

r10k::postrun_command and r10k::prerun_command update the puppet.conf file with post/pre run commands. The path that they use to find where puppet.conf lives is r10k::params::puppetconf_path which is _incorrect_ for anyone using Puppet 4 as Puppet 4 and PE now use the same configuration path of /etc/puppetlabs/puppet. My only option for getting either module to work (I use r10k::postrun_command) was to setup a symlink of /etc/puppet -> /etc/puppetlabs/puppet

**Comment by TheMeier** [comment]
oh sorry so i certainly should make a separte issue...

**Comment by acidprime** [comment]
Yep I plan on addressing this in a 3.0 release

**Comment by acidprime** [comment]
This now has conditional logic

**Comment by tykeal** [comment]
Is /etc/puppetlabs/r10k supposed to be automatically configured somehow with Puppet4? The path doesn't exist after installation of puppet-agent or puppetserver from the PC1 repos on my CentOS7 test environment and updating to the new version of the module it starts bombing because of the missing directory.

**Comment by acidprime** [comment]
It is in PE but thats because r10k is shipped with PE

https://github.com/TheMeier/r10k/blob/f4d2e0821a33549a8ad956753087d234afbe9ab9/manifests/config.pp#L82-L91


I am willing to entertain a PR that close to the above ^^ but likely without the /etc/puppetlabs as that should always exist,
