### ISSUE TITLE
Webhook issues for init service without hasstatus=> false

### ISSUE THREAD

**Issue by esalberg** [acidprime/r10k#188]
I just upgraded to the latest version of the module in conjunction with upgrading to PE 3.8 (staying with the module for the webhook, etc.).

The webhook seems to stop and start fine by hand.  However, Puppet tries to start the service every time.  If I try to get the status by hand, I get a segfault, e.g.::

[root@linvm2153-1 webhook]# service webhook status
/sbin/service: line 66: 28699 Segmentation fault      (core dumped) env -i PATH="$PATH" TERM="$TERM" "${SERVICEDIR}/${SERVICE}" ${OPTIONS}

I did some digging into pull requests and noticed that the hassstatus => false parameter was removed due to adding systemd support.  Should that be added back in for systems using init, or at least as an option, or is should the status command work and disabling status is hiding an underlying issue?

Pull request referenced:
https://github.com/acidprime/r10k/pull/178

**Comment by tampakrap** [comment]
I'm pretty sure I tested the initscript as well before submitting that PR, I'll re-test and will report back

**Comment by ayohrling** [comment]
Can confirm on my end this is still happening, I'm attempting to run down the seg fault issue now.

**Comment by ayohrling** [comment]
Alright, RHEL 6/CentOS 6 status from /etc/init.d/functions does not support -p; the syntax is status <binary> [pidfile]

I am putting together a change and a PR to push in a moment.

**Comment by ayohrling** [comment]
Pushed PR 194 to resolve this.

**Comment by acidprime** [comment]
closing please re-open if you can reproduce

**Comment by acidprime** [comment]
also closing as #194 has been merged
