### ISSUE TITLE
Webhook returns status 200 even if deploy fails

### ISSUE THREAD

**Issue by brandonweeks** [acidprime/r10k#195]
There is a lack of error handling in the webhook deploy method. If there is an exception in the deploy process, it should catch the exception and return http 500 instead.

Here is an example of an unhandled exception:

[2015-06-22 13:39:28] INFO  authenticated: puppet
[2015-06-22 13:39:28] ERROR message: 
/usr/share/rubygems/rubygems/dependency.rb:296:in `to_specs': Could not find 'multi_json' (~> 1.10) among 16 total gem(s) (Gem::LoadError)
	from /usr/share/rubygems/rubygems/specification.rb:1209:in `block in activate_dependencies'
	from /usr/share/rubygems/rubygems/specification.rb:1198:in `each'
	from /usr/share/rubygems/rubygems/specification.rb:1198:in `activate_dependencies'
	from /usr/share/rubygems/rubygems/specification.rb:1180:in `activate'
	from /usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/bin/r10k:22:in `<main>'
 trace: ["/usr/local/bin/webhook:164:in `deploy'", "/usr/local/bin/webhook:118:in `block in <class:Server>'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'", "/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'", "/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'", "/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'", "/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'", "/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'", "/usr/local/share/gems/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'", "/usr/local/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'", "/usr/local/share/gems/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'", "/usr/local/share/gems/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'", "/usr/share/ruby/webrick/httpserver.rb:138:in `service'", "/usr/share/ruby/webrick/httpserver.rb:94:in `run'", "/usr/share/ruby/webrick/server.rb:295:in `block in start_thread'"]
[2015-06-22 13:39:28] DEBUG close: 172.30.100.134:55550

**Comment by rnelson0** [comment]
Will this provide some sort of feedback in the PR, or only in the log for the hook?

**Comment by brandonweeks** [comment]
@rnelson0 not sure exactly what you mean. The error will output to /var/log/webhook/access.log where the webhook is hosted, it will also return {"status":"fail","message": ...} in the body of the JSON response which is viewable in our case via the GitHub interface.

**Comment by rnelson0** [comment]
Where in the GitHub interface? Will it show in the PR comments (i.e. here) or only in the settings -> hook section? Where would the failure be visible to humans?

**Comment by acidprime** [comment]
only in settings

**Comment by brandonweeks** [comment]
In the "Recent Deliveries" section under Settings -> Webhooks & Services. It's helpful for troubleshooting, since the delivery will show as failed so you know to look at the response for details on why it failed. The webhook returning 200 and GitHub reporting success threw me off when I was setting up webhook initially, since I thought it was working when it really never was.

**Comment by rnelson0** [comment]
Thanks for the clarity!
