### ISSUE TITLE
webhook.yaml recreated on every puppet run

### ISSUE THREAD

**Issue by poikilotherm** [acidprime/r10k#209]
Hi there,

I am building a new Puppetmaster with Puppetserver 3.8.1 and want to use the webhook for deployment. The Puppetmaster runs on CentOS 7 (system ruby 2.0). Puppetserver uses JRuby which states to be compatible with Ruby 1.9.

On every puppet agent run on the master machine the `webhook.yaml` config is recreated. I think this is related to #25, as the `webhook_hash` is converted to YAML via `@webhook_hash.to_yaml`. JRuby seems to behave a bit different than pure Ruby.

Shall I open a PR fixing this?

**Comment by poikilotherm** [comment]
I just wrote a spec test to check for this behaviour on different rubies. The issue is not present with JRuby 1.7.19, but I definitely can recreate this isse with current Puppetserver 3.8.1, which is using Clojure + JRuby 1.7.20 according to the docs/ticket system.

(JRuby 1.7.20 is not yet usable with RVM, so I didn't test that...)

With Ruby 1.8.7, this issue is present as with #25. Maybe cleanup this, anyway?

BTW, merely a note to myself: found a mistake in config.pp: certpath is doubled.

**Comment by poikilotherm** [comment]
@acidprime Could you have a look at this and tell me how I shall proceed?

(I'm currently on vacation, but watching things...)

**Comment by dforste** [comment]
Is there compelling reason to use the to_yaml from the yaml library? Do we expect to have nested variables? I would think something like the following would suffice. 
```
<% @webhook_hash.sort.each do |key,value| -%>
    <%=key-%>: <%=value%>
<% end -%>
```

**Comment by acidprime** [comment]
Puppet Server is support to act like Ruby 1.9...

**Comment by acidprime** [comment]
I run this setup at home via PE and don't have this issue, wonder if its something about the Puppet Server installation.

**Comment by poikilotherm** [comment]
I'm running this as FOSS version (v1.1.1-1.el7). I have no clue how I could reproduce this, so I will stick with @dforste and fix it anyway. Will include proper validations, etc.
