### ISSUE TITLE
Feature Request: custom fact location of r10k binary

### ISSUE THREAD

**Issue by poikilotherm** [acidprime/r10k#210]
Hi there,

I would like to see a custom fact that sends the master the absolute path of the r10k binary.

My use case is the proper definition of a sudo rule for the webhook service user, where I need an absolute path (forced by sudo config enforcements).

Shall I create an PR addressing this issue? I can spend time on other things if you guys don't like the idea... ;-)

**Comment by acidprime** [comment]
Yeah I would love this as I actually would want to use in the mcollective agent too
