### ISSUE TITLE
Feature Request: add a r10k postrun hook for directory environment cache invalidation

### ISSUE THREAD

**Issue by poikilotherm** [acidprime/r10k#211]
Hi there,

according to the docs, it is good common practice to set `environment_timeout = unlimited` in directory environments and on updates do things to tell the puppet master that code has changed.
(see http://docs.puppetlabs.com/puppet/4.1/reference/environments_configuring.html#environmenttimeout and older versions like http://docs.puppetlabs.com/puppet/3.8/reference/environments_configuring.html#environmenttimeout)

I would appreciate a script that handles this called by the r10k postrun. For now I would only enable the API call to Puppetserver (http://docs.puppetlabs.com/puppetserver/latest/admin-api/v1/environment-cache.html), but this could be extended to support passenger/rack deployments, too.

Shall I open a PR addressing this issue? Same thing with time slots as for #210... ;-)

**Comment by acidprime** [comment]
postrun currently runs at the end of all environments being synced but this endpoint can be used per environment, until the two are updated this will likely be semi inefficient, though adrian is working on per environment hooks
