### ISSUE TITLE
hiera_eyaml on pe 3.7+  is broken.

### ISSUE THREAD

**Issue by brettswift** [acidprime/r10k#216]
https://support.puppetlabs.com/requests/12441

That ticket above (I realize only puppetlabs employees can see it)  was a bug we ran into when upgrading to PE 3.8. 

hiera_eyaml wasn't being installed in the correct ruby. 

Our solution was to do this: 

```
[root@devcorepptl002 ~]# /opt/puppet/bin/puppetserver gem install hiera-eyaml 
Fetching: trollop-2.1.2.gem (100%) 
Successfully installed trollop-2.1.2 
Fetching: highline-1.6.21.gem (100%) 
Successfully installed highline-1.6.21 
Fetching: hiera-eyaml-2.0.8.gem (100%) 
Successfully installed hiera-eyaml-2.0.8 
3 gems installed
```

When using PE3.7+ the hiera_eyaml seems to require being installed using the pe_pupppetserver_gem provider. 

I think this is something that this r10k module should be taking care of.

**Comment by acidprime** [comment]
@brettswift I don't really think eyaml is in the scope of this module, can you explian why? I would say hunner/hiera would be a better place for that
