### ISSUE TITLE
Where can i find pe_r10k ?

### ISSUE THREAD

**Issue by dichque** [acidprime/r10k#239]
I have 3.8.1 install and am in process of using r10k gem from PE. 

Quoting your recommendation:
Note: It is recommended you migrate to using the pe_r10k module which is basically a clone of this modules features and file tickets for anything missing.

Where can i find this pe_r10k module ?

**Comment by acidprime** [comment]
@dichque PE 3.8.1 does not ship with pe_r10k, you have to upgrade to 2015.2 and higher to find it. You can use this module in 3.8.1 though as there is logic that manages the configuration file but stops managing the package as thats vendored.
