### ISSUE TITLE
Q: can get the agent to activate PE 2015.2

### ISSUE THREAD

**Issue by MAXxATTAXx** [acidprime/r10k#243]
Hi,

i'm trying to use you r10k::mcollective agent but i'm facing a problem when trying to get the agent to activate. Looking at the code, this agent gets activated when `which r10k 2> /dev/null` returns a value. I have failed hard to get this going for me. 

I tried detecting the user that was running the daemon in order to do a `export PATH=$PATH:/opt/puppetlabs/bin/`.
I also changed /etc/bashrc to do the export in order to have all users have r10k available, but it is not working either.

Do you have a tip on what could be preventing the ruby code from finding the r10k command?

Notes: Centos 6 box using the suggested pe_r10k class to install r10k in master nodes.

**Comment by acidprime** [comment]
> I tried detecting the user that was running the daemon in order to do a export PATH=$PATH:/opt/puppetlabs/bin/.

@MAXxATTAXx mcollective will be running as root not the daemon. I know thats confusing but basically the daemon is calling mcollective and mcollective is running as root. I assume deamon you mean webhook too in this context.

**Comment by acidprime** [comment]
closing this if thats the fix, please re-open if not
