### ISSUE TITLE
images in README.md broken

### ISSUE THREAD

**Issue by mmckinst** [acidprime/r10k#263]
http://imageshack.com/a/img661/6302/qQwIrw.gif
http://imageshack.com/a/img674/3070/NWvnSn.png

probably related: https://twitter.com/ImageShack/status/698602422931816448

**Comment by mmckinst** [comment]
The cool animated webhook image is still broken: https://github.com/acidprime/r10k/blob/91bde83941a30c1049f639c1a07ad406f7990301/README.md#webhook-support

I couldn't find a copy of it out there. Hopefully you or someone else has one.

**Comment by acidprime** [comment]
Found an old gist , also thanks for saying its "cool".
