### ISSUE TITLE
mcollective agent unable to find r10k binary

### ISSUE THREAD

**Issue by jessereynolds** [acidprime/r10k#275]
on RHEL 6.6 and with PE 2016.1.1 standalone installed, the r10k mcollective agent is unable to see the r10k binary in the PATH. You see this in the mcollective log:

```
E, [2016-05-10T22:37:28.412524 #7719] ERROR -- : r10k.rb:11:in `block in <class:R10k>' r10k binary not found in PATH
```

/usr/local/bin/r10k is present but /usr/local/bin is not in the mcollective agent's PATH when it's executing anymore (tested on a puppet-debugging-kit vm as well as on a hand built RHEL 6 server).

**Comment by jessereynolds** [comment]
A workaround for this is to make another symlink for r10k at /usr/bin/r10k eg:

```puppet
class profiles::r10k {

  class {'r10k::webhook::config':
    enable_ssl => false,
    protected  => false,
  }

  class {'r10k::webhook':
    require    => Class['r10k::webhook::config'],
  }

  include r10k::mcollective

  # refer https://github.com/acidprime/r10k/issues/275
  file {'r10k_symlink_usr_bin':
    ensure => link,
    path   => '/usr/bin/r10k',
    target => '/opt/puppetlabs/bin/r10k',
    owner  => 'root',
  }
}
```

**Comment by alexjfisher** [comment]
Looks like a duplicate of https://github.com/acidprime/r10k/issues/273 ?

**Comment by rnelson0** [comment]
Confirmed duplicate.
