### ISSUE TITLE
'require git' appears to be unnecessary

### ISSUE THREAD

**Issue by tprobinson** [acidprime/r10k#286]
I've recently set up a FOSS Puppet on Ubuntu, version 4.7.0. When using this module, I get the following error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find class ::git for pupt1.lupusllc.com at /etc/puppetlabs/code/environments/production/modules/r10k/manifests/install/puppet_gem.pp:4:3
```

If I open that file and remove `require git`, the module works seemingly normally. Here's the class definition I'm using:

```puppet
class { 'r10k':
  version           => '2.4.3',
  sources           => {
    'puppet' => {
      'remote'  => '<my control-repo.git>',
      'basedir' => $::settings::environmentpath,
      'prefix'  => false,
    }
  },
  manage_modulepath => false,
}
```

Have I done something wrong in this declaration that I've confused it?

**Comment by rnelson0** [comment]
@tprobinson There is a [dependency on puppetlabs/git](https://github.com/acidprime/r10k/blob/master/metadata.json#L82) for this module, and the error points to that module not being available in your environment. It makes sure that git is installed and usable by r10k. I assume your system already had git installed, so you had no problem, but if you had a more minimal install of Ubuntu that did not include the git package, you would have run into issues.

As there is no assurance that a node this module is applied to already has git, r10k retains that dependency to ensure the proper state is satisfied. You should update your puppetfile (or other bootstrap method) to deploy puppetlabs/git into the environment before applying the r10k class. Let us know how that works out. Thanks!

**Comment by tprobinson** [comment]
Ah, that works. Somehow I wasn't able to find Puppetlabs' Git module before. Sorry about the issue!
