### ISSUE TITLE
prerun_command setting has no dependencies

### ISSUE THREAD

**Issue by supercow** [acidprime/r10k#36]
There are many resources in the R10k module that are required for R10k to run, and if any of them fail, r10k commands cannot be executed. The `prerun_command`, however, will currently be managed regardless of any configuration failures in these critical resources.

This may not be a simple fix by adding a require statement to the `r10k::prerun_command` resources, since the order in which `r10k::prerun_command` class is included is up to the user, meaning the required resources may not be available int he catalog yet. If we are comfortable with forcing the user to declare `r10k::prerun_command` after `r10k` is declared, or with forcing prerun_command through a parameter to r10k, that would be a quick fix.

Using defined() isn't really an option due to this same parse-ordering problem.

**Comment by acidprime** [comment]
closing as won't fix for the time being as no one has reported this being a real world problem and need to cut the backlog
