### ISSUE TITLE
mco doesn't deploy modules when using forge functionality of Puppetfile

### ISSUE THREAD

**Issue by vchepkov** [acidprime/r10k#65]
Hi,

It seems r10 mco module doesn't deploy modules from Puppet file.

r10k deploy environment -p
deploys modules just fine 

on other hand

sudo -u peadmin /opt/puppet/bin/mco r10k synchronize
doesn't.

**Comment by acidprime** [comment]
https://github.com/acidprime/r10k/commit/771548509f8a72c41e00c79b025826550dee684e

**Comment by acidprime** [comment]
Released in https://github.com/acidprime/r10k/releases/tag/v2.5.3
