### ISSUE TITLE
Option to NOT install the r10k package

### ISSUE THREAD

**Issue by fcntl** [acidprime/r10k#74]
Ge this horrible broken error when trying to install r10k gem using this module:

Error: Could not update: Execution of '/usr/bin/gem install -v 1.1.0 --no-rdoc --no-ri r10k ' returned 1: ERROR:  Can't use --version w/ multiple gems. Use name:ver instead.
Wrapped exception:
Execution of '/usr/bin/gem install -v 1.1.0 --no-rdoc --no-ri r10k ' returned 1: ERROR:  Can't use --version w/ multiple gems. Use name:ver instead.
Error: /Stage[main]/R10k::Install/Package[r10k]/ensure: change from 1.3.2 to 1.1.0 failed: Could not update: Execution of '/usr/bin/gem install -v 1.1.0 --no-rdoc --no-ri r10k ' returned 1: ERROR:  Can't use --version w/ multiple gems. Use name:ver instead.
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y list rubygems-bundler' returned 1: Error: No matching Packages to list
Error: /Stage[main]/Ruby::Dev/Package[rubygems-bundler]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y list rubygems-bundler' returned 1: Error: No matching Packages to list

It worked fine when I was installing it using my own Puppet package class. Please add an option to NOT install the r10k package.

**Comment by acidprime** [comment]
This is likely going to be needed for v3 anyway due to some PE changes.
