### ISSUE TITLE
[Bug] Webhook does not support Ping event from GitHub

### ISSUE THREAD

**Issue by elyscape** [acidprime/r10k#89]
When setting up a new webhook service on GitHub, it sends a [Ping event](https://developer.github.com/webhooks/#ping-event) to the service to test the connection.  The webhook service provided here doesn't support this, and gives an HTTP 500 error and [a bunch of HTML with the issue](http://scratchpad.io/substantial-cellar-1663).  It looks like the problem is with [line 84 of the webhook code](https://github.com/acidprime/r10k/blob/master/files/webhook#L84):

    branch = ( data['ref'] || data['refChanges'][0]['refId'] ).split("/").last

ref and refChanges don't exist in a ping event, so this explodes.

**Comment by brandonweeks** [comment]
This was actually fixed in #201 after I created the duplicate issue #200.
