### ISSUE TITLE
r10k::webhook::config provides support for changing config file path, but the webhook script has this hardcoded

### ISSUE THREAD

**Issue by elyscape** [acidprime/r10k#90]
r10k::webhook::config [provides the ability to change the config file path](https://github.com/acidprime/r10k/blob/master/manifests/webhook/config.pp#L26), but the webhook script [has the default location hardcoded](https://github.com/acidprime/r10k/blob/master/files/webhook#L23).  As a result, changing the config file path results in the webhook script failing or, if the default file path was used previously, using whatever outdated config file was last used in the default location.

**Comment by acidprime** [comment]
closing this for now, can reopen as need if the community requests it

**Comment by elyscape** [comment]
I would at least for now recommend removing the `configfile` parameter on `r10k::webhook::config` in the meantime, as all it does is break the webhook.
